baseURL = "https://dualclassics.com/"
languageCode = "en-us"
title = "Dual Classics"
theme = "dualkids"
enableRobotsTXT = true
enableGitInfo = true

[pagination]
  pagerSize = 20

[params]
  brandTitle = "Dual Classics"
  brandTagline = "Classic stories in simple English + Español"
  primaryColor = "#FF6B6B"      # watermelon
  secondaryColor = "#4ECDC4"    # teal
  accentColor = "#FFE66D"       # sunny yellow
  footerNote = "Public domain classics, retold for kids."
  copyrightStartYear = 2025

  [params.seo]
    siteDescription = "Kid-friendly bilingual classics (EN + ES) — simple, side-by-side texts for families and classrooms."
    # Replace with a wide 1200x630 image when available
    defaultOGImage = "https://imagedelivery.net/uoQWLs2DQGCKz-4i8TTorQ/cec67720-b2ed-43fc-4099-c0987a94fb00/public"
    # Optional: your Twitter handle without @ (uncomment and set)
    # twitter = "dualclassics"

  [params.organization]
    name = "Dual Classics"
    streetAddress = "1034 N. Madison Ave."
    addressLocality = "Pasadena"
    addressRegion = "CA"
    postalCode = "91104"
    addressCountry = "US"
    logo = "https://imagedelivery.net/uoQWLs2DQGCKz-4i8TTorQ/87359f19-0b95-4d50-3bf4-f35ff540e400/public"
    founders = ["Christian Rodgers", "Lyndsy Rodgers"]
    # Optional extras:
    # sameAs = ["https://dualclassics.com/"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[permalinks]
  books = "/books/:sections/:slug/"

[outputs]
  home = ["HTML"]

disableKinds = ["taxonomy", "term"]

# Disable taxonomies entirely to avoid taxonomy layout warnings
[taxonomies]

[menu]
  [[menu.main]]
    name = "Books"
    url = "/books/"
    weight = 1
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2

[sitemap]
  changefreq = "weekly"
  priority = 0.6
  filename = "sitemap.xml"
